import * as XLSX from 'xlsx';
import * as fs from 'fs';
import * as path from 'path';

// Read the Excel file from data/master directory
const excelPath = path.join(__dirname, '../../data/master/Sign Board Master - MS Part.xlsx');
const workbook = XLSX.readFile(excelPath);
const sheetName = 'Master Sign Structures (latest)';
const worksheet = workbook.Sheets[sheetName];

if (!worksheet) {
  console.error(`Sheet "${sheetName}" not found in Excel file`);
  process.exit(1);
}

// Convert to JSON
const rawData = XLSX.utils.sheet_to_json(worksheet);

// Interface for the row data
interface SignMsMasterRow {
  shape: string;
  sizeCode: string;
  postLengthM: number;
  frameLengthM: number;
  remarks: string;
}

// Parse and normalize the data
const parsedRows: SignMsMasterRow[] = [];

for (const row of rawData as any[]) {
  // Skip header rows or empty rows
  if (!row['Shape of Board'] || !row['Size\r\n(in mm)']) {
    continue;
  }

  const shapeRaw = String(row['Shape of Board']).trim();
  const sizeRaw = row['Size\r\n(in mm)'];
  const postLength = row['__EMPTY']; // Post Length (in Mtrs)
  const frameLength = row['__EMPTY_3']; // Frame Length
  const remarks = row['Remarks'] ? String(row['Remarks']).trim() : '';

  // Normalize shape
  let shape = '';
  if (shapeRaw.toLowerCase().includes('circular')) {
    shape = 'Circular';
  } else if (shapeRaw.toLowerCase().includes('triangular') || shapeRaw.toLowerCase().includes('triangle')) {
    shape = 'Triangle';
  } else if (shapeRaw.toLowerCase().includes('octagonal') || shapeRaw.toLowerCase().includes('octogonal')) {
    shape = 'Octagonal';
  } else if (shapeRaw.toLowerCase().includes('rectangular')) {
    shape = 'Rectangular';
  } else {
    continue; // Skip unknown shapes
  }

  // Normalize size code
  let sizeCode = '';
  if (typeof sizeRaw === 'number') {
    sizeCode = String(sizeRaw);
  } else {
    // Handle "450 x 600" format - normalize to "450x600"
    const sizeStr = String(sizeRaw).trim();
    sizeCode = sizeStr.replace(/\s*x\s*/gi, 'x').toLowerCase();
  }

  // Parse lengths (handle both numbers and strings)
  const postLengthM = postLength ? parseFloat(String(postLength)) : 0;
  const frameLengthM = frameLength ? parseFloat(String(frameLength)) : 0;

  parsedRows.push({
    shape,
    sizeCode,
    postLengthM,
    frameLengthM,
    remarks,
  });
}

// Remove duplicates based on shape + sizeCode
const uniqueRows: SignMsMasterRow[] = [];
const seen = new Set<string>();

for (const row of parsedRows) {
  const key = `${row.shape}|${row.sizeCode}`;
  if (!seen.has(key)) {
    seen.add(key);
    uniqueRows.push(row);
  }
}

// Sort by shape, then by sizeCode for better readability
uniqueRows.sort((a, b) => {
  if (a.shape !== b.shape) {
    return a.shape.localeCompare(b.shape);
  }
  return a.sizeCode.localeCompare(b.sizeCode);
});

// Generate TypeScript file content
const tsContent = `// Auto-generated from Sign Board Master - MS Part.xlsx
// Run: npm run convert:ms
// DO NOT EDIT THIS FILE MANUALLY - Regenerate from Excel source

export interface SignMsMasterRow {
  shape: string;
  sizeCode: string;
  postLengthM: number;
  frameLengthM: number;
  remarks: string;
}

export const signMsMaster: SignMsMasterRow[] = ${JSON.stringify(uniqueRows, null, 2)};

/**
 * Helper function to get MS dimensions by shape and size code
 * @param shape - Board shape (e.g., "Circular", "Triangle", "Octagonal", "Rectangular")
 * @param sizeCode - Size code (e.g., "600", "450x600", "900x1200")
 * @returns Matching row or null if not found
 */
export function getMsDimensions(shape: string, sizeCode: string): SignMsMasterRow | null {
  // Normalize inputs
  const normalizedShape = shape.trim();
  const normalizedSizeCode = sizeCode.trim().toLowerCase().replace(/\\s*x\\s*/gi, 'x');
  
  // Find matching row
  return signMsMaster.find(row => {
    const rowShape = row.shape.toLowerCase();
    const rowSizeCode = row.sizeCode.toLowerCase().replace(/\\s*x\\s*/gi, 'x');
    
    return rowShape === normalizedShape.toLowerCase() && rowSizeCode === normalizedSizeCode;
  }) || null;
}
`;

// Write to data/master directory
const outputPath = path.join(__dirname, '../../data/master/signMsMaster.ts');
fs.writeFileSync(outputPath, tsContent, 'utf8');

console.log(`✅ Generated ${uniqueRows.length} unique rows`);
console.log(`✅ Written to ${outputPath}`);
console.log(`\nSample rows (first 5):`);
console.log(JSON.stringify(uniqueRows.slice(0, 5), null, 2));
console.log(`\n✅ Conversion complete!`);

